# Generated by Django 5.2.8 on 2025-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno_emprestimo_delete_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
